# $HOME/.config/alacritty/alacritty.toml
#    .___         ___ ___                __            
#  __| _/_  _  __/   |   \_____    ____ |  | __  ______
# / __ |\ \/ \/ /    ~    \__  \ _/ ___\|  |/ / /  ___/
#/ /_/ | \     /\    Y    // __ \\  \___|    <  \___ \ 
#\____ |  \/\_/  \___|_  /(____  /\___  >__|_ \/____  >
#     \/               \/      \/     \/     \/     \/ 
# My Alacritty config! I like this one!
[window]

opacity = 0.95

#padding.x = 10
#padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[window.dimensions]
columns = 140
lines = 30

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"


#[font]

#normal.family = "Cascadia Code PL"
#bold.family = "Cascadia Code PL"
#italic.family = "Cascadia Code PL"
#bold_italic.family = "Cascadia Code PL"

#size = 15.0

